apiVersion: v1
kind: ResourceQuota
metadata:
  name: reema-resource-quota
  namespace: reema-tawazun
  labels: 
    name: reema
spec:
  hard:
    requests.cpu: 2
    requests.memory: 2G
    limits.cpu: 4
    limits.memory: 4G